version: "3"
services: 
      web: 
        container_name: "java-project"
        ports:
            - "8000:8000"
        build: .
        dependson: db

      db: 
        image: mysql:latest
        ports:
            - "3306:3306"
        environment:
          MYSQL_ROOT_PASSWORD: "rootpassword"
          MYSQL_DATABASE: "mydatabase"
          MYSQL_USER: "myuser"
          MYSQL_PASSWORD: "mypassword"
        volumes:
            - /users/apple/desktop/volume:/var/lib/mount/  

      volumes:
          mydata: